# Site settings
title: Jason Loveland's Blog
email: jloveland@users.noreply.github.com
description: "Jason Loveland's Blog"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jasonloveland
github_username:  jloveland

# Build settings
markdown: kramdown
